"""add is_moving to health

Revision ID: da7ab09871b8
Revises: a934f3630e0c
Create Date: 2026-05-19 21:54:33.408224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7ab09871b8'
down_revision: Union[str, Sequence[str], None] = 'a934f3630e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('is_moving', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health', 'is_moving')
    # ### end Alembic commands ###
